### ISSUE TITLE
Don't make DataView window modal

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#18]
Currently, the DataView window is always frontmost and always blocks any windows behind it.  This behavior should be changed.

**Comment by pheuer** [comment]
Fixed this today: window focus with pyqt5 is not well handled. If anyone's curious, the code block to fix this (added at the beginning) was: 

'self.show()
self.activateWindow()
self.raise_()`

Where self is the ApplicationWindow.
