### ISSUE TITLE
Feature Request: Select ranges in DataView by values instead of indices

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#3]
Would be very helpful to be able to set the ranges for the different axes in DataView (time, xaxis, etc) by their physical values rather than their indices.

**Comment by pheuer** [comment]
Agreed: do you have any thoughts on the least clunky way to do this in the UI? One option would be to have one set of "bounds" fields and then a radio button that switches back and forth between values and units?

**Comment by dschaeffer17** [comment]
I think the vast majority of the time people will want to set ranges by physical values, so as a first step you could just make this the default instead of indices.

Long term, since you already have ranges set up, I agree that a simple radio button between index and value would suffice.  If you really wanted to get fancy, you could add a new menu option to set various configuration choices.

**Comment by pheuer** [comment]
This feature has been added in the latest update!
