### ISSUE TITLE
DataView prints debugging? messages while running in terminal

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#6]
While running DataView in a terminal, it appears to print extraneous messages, perhaps from an earlier debugging process.  Examples include:

2 is in avg_axes
4 is in avg_axes
[2, 4]
[2, 4, 2, 4]

**Comment by pheuer** [comment]
Removed/silenced these in the latest update. Some (more helpful) debugging messages can be shown by setting a flag at the top of the program to True.
