### ISSUE TITLE
Feature Request: option to display axes in plot with different units

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#7]
DataView currently plots axes with a fixed unit (G, V, s, etc).  It would be convenient if different units could be selected, e.g. kG, ns, us, ms, mV, etc.

**Comment by pheuer** [comment]
Added this feature in the latest update! The conversion uses astropy, and strings must conform to the OGIP unit string convention (including standard metric prefixes etc.): 
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/general/ogip_93_001/

If anyone runs into an issue with this constraint, we can look into ways to extend the functionality.
