### ISSUE TITLE
Minor: Some text cutoff

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#8]
When running DataView in a terminal, some text is cutoff by default.  For example, "Data Range" is cutoff by the lower bound input box, and the "time: Values [...]" is cutoff by the "Val" radio button.

May be easiest to widen default window size to accommodate.  Widening window in current version doesn't correct issue.

**Comment by pheuer** [comment]
I'm setting the width of those text boxes manually: it looks like I just need to make them bigger (or allow them to change)? This should be an easy fix.

**Comment by dschaeffer17** [comment]
I think just making them bigger should be fine - no need to mess with dynamic sizing (unless you feel compelled to).

**Comment by pheuer** [comment]
Dynamic sizing is actually easier, but the way the layout works it makes everything else not line up, and we can't have that. 

I've made the field longer, so this should now be fixed.

**Comment by dschaeffer17** [comment]
"Data Range" is still cut off by first input field.

**Comment by pheuer** [comment]
Right you are: fixed.
